"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, Plus, Users, X } from "lucide-react";
type Meeting = {id:number;name:string}; type Entry={name:string;slots:number[];color:string};
const colors=["#6557e8","#e36b5d","#37a885","#d79a30","#4c87d9","#c65aa6"], days=["월","화","수","목","금","토","일"];
export default function Home(){const [meetings,setMeetings]=useState<Meeting[]>([]),[active,setActive]=useState<Meeting|null>(null),[entries,setEntries]=useState<Entry[]>([]),[modal,setModal]=useState<"create"|"availability"|null>(null),[newName,setNewName]=useState(""),[name,setName]=useState(""),[draft,setDraft]=useState<Set<number>>(new Set()),[error,setError]=useState(""),[saving,setSaving]=useState(false);
useEffect(()=>{fetch("/api/meetings").then(r=>r.ok?r.json():Promise.reject()).then(d=>{setMeetings(d);if(d[0])setActive(d[0])}).catch(()=>setError("저장에 실패했어요. 다시 시도해주세요"))},[]);
useEffect(()=>{if(active)fetch(`/api/availability?meetingId=${active.id}`).then(r=>r.ok?r.json():Promise.reject()).then(setEntries).catch(()=>setError("저장에 실패했어요. 다시 시도해주세요"))},[active]);
const counts=useMemo(()=>Array.from({length:336},(_,i)=>entries.reduce((n,e)=>n+(e.slots.includes(i)?1:0),0)),[entries]),max=Math.max(0,...counts); const toggle=(s:number)=>setDraft(c=>{const n=new Set(c);n.has(s)?n.delete(s):n.add(s);return n});
async function create(){if(!newName.trim())return;try{const r=await fetch("/api/meetings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:newName})});if(!r.ok)throw 0;const m=await r.json();setMeetings(x=>[...x,m]);setActive(m);setModal(null);setNewName("")}catch{setError("저장에 실패했어요. 다시 시도해주세요")}}
async function save(){if(!active||!name.trim()||!draft.size)return;setSaving(true);try{const r=await fetch("/api/availability",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({meetingId:active.id,name,slots:[...draft]})});if(!r.ok)throw 0;const found=entries.findIndex(e=>e.name===name);const item={name,slots:[...draft],color:colors[(found<0?entries.length:found)%colors.length]};setEntries(x=>[...x.filter(e=>e.name!==name),item]);setModal(null);setName("");setDraft(new Set())}catch{setError("저장에 실패했어요. 다시 시도해주세요")}finally{setSaving(false)}}
if(!active)return <main className="app-shell"><Header add={()=>setModal("create")}/><section className="empty"><span className="empty-icon"><CalendarDays size={27}/></span><h1>아직 모임이 없어요.</h1><p>친구들과 맞출 스터디룸 시간을 추가해보세요.</p><button className="primary" onClick={()=>setModal("create")}><Plus size={17}/> 모임 추가하기</button></section>{modal==="create"&&<Create value={newName} set={setNewName} close={()=>setModal(null)} submit={create}/>}</main>;
return <main className="app-shell"><Header add={()=>setModal("availability")}/><section className="workspace"><div className="heading"><div><p className="eyebrow">9월 셋째 주 · 스터디룸 예약</p><h1>{active.name}</h1><p className="helper">빈 칸을 클릭하면 내 가능 시간을 입력할 수 있어요.</p></div><div className="summary"><Users size={17}/><strong>{entries.length}명</strong> 참여 가능</div></div><div className="legend"><span className="legend-dot"/><b>가장 많은 인원이 가능한 시간</b>{max>0&&<span className="best-note">최대 {max}명</span>}</div><div className="timetable-wrap"><div className="timetable"><div className="corner">시간</div>{days.map((d,i)=><div className="day-head" key={d}><b>{d}</b><span>9/{14+i}</span></div>)}{Array.from({length:48},(_,r)=><div className="time-row" key={r}><div className="time-label">{r%2===0?`${String(8+r/2).padStart(2,"0")}:00`:""}</div>{days.map((_,d)=>{const slot=d*48+r,c=counts[slot],best=max>0&&c===max;return <button className={`slot ${best?"best":""}`} key={slot} onClick={()=>setModal("availability")}>{c>0&&<span className="slot-count">{c}</span>}</button>})}</div>)}</div></div><aside className="people-panel"><div className="panel-title"><span>참여자</span><span>{entries.length}</span></div>{entries.length?entries.map(e=><div className="person" key={e.name}><i style={{background:e.color}}/><span>{e.name}</span><small>{e.slots.length*30}분</small></div>):<p className="no-people">아직 입력한 사람이 없어요.</p>}</aside></section>{modal==="availability"&&<section className="modal-backdrop"><div className="availability-modal" role="dialog"><button className="close" onClick={()=>setModal(null)}><X size={20}/></button><p className="eyebrow">내 시간 추가하기</p><h2>가능한 시간을 표시해 주세요</h2><label>이름<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="예: 민지"/></label><p className="picker-help">아래 시간표에서 가능한 시간을 클릭하세요.</p><div className="mini-grid">{Array.from({length:336},(_,s)=><button key={s} className={draft.has(s)?"selected":""} onClick={()=>toggle(s)}/>)}</div><div className="modal-footer"><span>{draft.size?`${draft.size*30}분 선택됨`:"시간을 선택해 주세요"}</span><button className="primary" disabled={saving||!name.trim()||!draft.size} onClick={save}>{saving?"저장 중…":<><Check size={17}/> 저장하기</>}</button></div></div></section>}{modal==="create"&&<Create value={newName} set={setNewName} close={()=>setModal(null)} submit={create}/>} {error&&<div className="toast">{error}<button onClick={()=>setError("")}><X size={15}/></button></div>}</main>}
function Header({add}:{add:()=>void}){return <header className="topbar"><div className="brand"><span className="brand-mark"><CalendarDays size={18}/></span><span>모여, 스터디</span></div><button className="add-button" onClick={add}><Plus size={18}/><span>가능 시간 입력</span></button></header>}
function Create({value,set,close,submit}:{value:string;set:(v:string)=>void;close:()=>void;submit:()=>void}){return <section className="modal-backdrop"><div className="create-modal" role="dialog"><button className="close" onClick={close}><X size={20}/></button><span className="create-icon"><Plus size={22}/></span><h2>새 모임 만들기</h2><p>친구들과 맞출 모임 이름을 적어주세요.</p><label>모임 이름<input autoFocus value={value} onChange={e=>set(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="예: 데이터베이스 스터디"/></label><button className="primary full" disabled={!value.trim()} onClick={submit}>모임 만들기</button></div></section>}
